#!/usr/bin/env python2

import sdf
import re
import os
import shutil
import argparse
import numpy as np
import multiprocessing as mp
from multiprocessing import Manager
from distutils import spawn

import matplotlib
matplotlib.use('Agg')  
from matplotlib import pylab
from matplotlib.colors import LogNorm
from mpl_toolkits.axes_grid1 import make_axes_locatable
import matplotlib.pyplot as plt

def argument_parse():
  parser = argparse.ArgumentParser(description='Find density FFT')
  parser.add_argument('sdffiles', metavar='NNNN', type=int, nargs='+',
                   help='SDF file(s) to be processed')
  parser.add_argument('--lim', dest='limits', type=float, nargs=2,
    metavar=("xmin", "xmax"), help='limits of FFT window')
  return(parser.parse_args())

def process_file(filename):
  try:
    sdf_data = sdf.SDF(filename).read()
  except:
    print("Failed to open file {0}".format(filename))
    exit()
  return sdf_data

def fft_process(filename):
  sdf_data = process_file(filename)
  
  x = sdf_data['Grid/Grid/X']
  dens = sdf_data['Derived/Number_Density/electron']
  
  plotx = x
  plotdens = dens

  print(x)
  print(dens)

  print("Initial x.shape: {}".format(x.shape))
  print("Initial dens.shape: {}".format(dens.shape))

  if args.limits:
    xmin = (np.abs(x-args.limits[0])).argmin()
    xmax = (np.abs(x-args.limits[1])).argmin()
    print("x limits, {}: {} -- {}: {}".format(xmin,x[xmin],xmax,x[xmax]))
    plotx = x[xmin:xmax+1]
    plotdens = dens[xmin:xmax+1]

  print(plotx)
  print(plotdens)

  print("New x.shape: {}".format(plotx.shape))
  print("New dens.shape: {}".format(plotdens.shape))

  densfft = np.fft.fftshift(np.absolute(np.fft.fft(plotdens)))
  freqx = np.fft.fftshift(np.fft.fftfreq(len(plotx),np.abs(plotx[3]-plotx[2])))

  plt.figure()
  ax = []
  ax.append(plt.subplot2grid((2,2),(0,0),colspan=2))
  ax.append(plt.subplot2grid((2,2),(1,0),colspan=2))
  im = []
  im.append(ax[0].plot(plotx,plotdens))
  im.append(ax[1].plot(freqx,densfft))
  x_px = 1920
  y_px = 1080
  y_size=8
  x_size=y_size*x_px / y_px
  plt.gcf().set_size_inches(x_size,y_size)
  savepath = ("{0}_fft".format(filename[:-4]))
  print(savepath)
  plt.savefig(savepath,dpi=x_px/x_size)
  plt.close()


def main():
  global args
  args = argument_parse()
  
  for filenum in args.sdffiles:
    filename = "{0:04d}.sdf".format(filenum)
    fft_process(filename)
    
   
if __name__ == "__main__":
  main()

