#!/usr/bin/env python2

import matplotlib
matplotlib.use('Agg')  
from matplotlib.colors import LogNorm
from mpl_toolkits.axes_grid1 import make_axes_locatable
import matplotlib.pyplot as plt
import numpy as np
import sdf
import multiprocessing as mp
import os
import shutil
from distutils import spawn

def main():

  try:
    shutil.rmtree('movie')
  except:
    pass
  try:
    os.mkdir('movie')
  except:
    print('failed to make movie directory. check perms?')
    exit()
  sdf_list = [f for f in os.listdir(os.getcwd()) if f.endswith('.sdf')]
  worker_pool = mp.Pool(processes=mp.cpu_count())
  map(mkimage, sdf_list)
  if spawn.find_executable('avconv'):
    converter = spawn.find_executable('avconv')
  elif spawn.find_executable('ffmpeg'):
    converter = spawn.find_executable('ffmpeg')
  else:
    print("Couldn't find ffmpeg/avconv :(\n"
          "you're on your own for making the movie")
    os.exit(1)

  conv_args = [converter,'-r', '1', '-i', 'movie/%04d.png', '-c:v', 'libx264',
              '-r', '30', '-pix_fmt', 'yuv420p','-y', 
              ''.join((os.path.basename(os.getcwd()),'_ex.mp4'))]
  spawn.spawn(conv_args)

def mkimage(filename):

  filedata = sdf.SDF(filename).read()
  x = filedata['Grid/Grid/X']
  y = filedata['Grid/Grid/Y']
  dens = filedata['Derived/Number_Density/electron'].transpose()
  fig = plt.figure()
  ax = []
  ax.append(plt.subplot2grid((2,1), (0,0)))
  ax.append(plt.subplot2grid((2,1), (1,0)))
  ymin_loc = np.abs(y).argmin()
  lineout_dens = dens[ymin_loc]
  print(x.shape)
  print(lineout_dens.shape)
  ax[0].plot(x, lineout_dens)
  im = ax[1].imshow(dens, vmin=dens.min(), vmax=dens.max(), extent=[x.min(), x.max(), y.min(), y.max()])
  divider = make_axes_locatable(ax[1])
  cax = divider.append_axes('right', size='5%', pad=0.05)
  plt.colorbar(im, cax=cax)
  x_px = 1920
  y_px = 1080
  y_size=10
  x_size=y_size*x_px / y_px
  plt.gcf().set_size_inches(x_size,y_size)
  savepath = os.path.join('movie',(filename[:-4]))
  print(savepath)
  plt.savefig(savepath,dpi=x_px/x_size)
  plt.close()
  
if __name__ == '__main__':
  main()
