#!/usr/bin/env python2

import sdf
import re
import os
import shutil
import numpy as np
import multiprocessing as mp
from multiprocessing import Manager
from distutils import spawn

import matplotlib
matplotlib.use('Agg')  
from matplotlib import pylab
from matplotlib.colors import LogNorm
from mpl_toolkits.axes_grid1 import make_axes_locatable
import matplotlib.pyplot as plt

match_subset = re.compile("Particles/ID/subset_(?P<subset>.*)/electron")

manager = Manager()
shared_data = manager.list()

def main():
  global shared_data
  try:
    os.mkdir('movie')
  except:
    print('movie directory already exists, will not overwrite')
    exit()
  sdf_list = [f for f in os.listdir(os.getcwd()) if f.endswith('.sdf')]
  worker_pool = mp.Pool(processes=mp.cpu_count())
  pulse_energy = worker_pool.map(process_file, sdf_list)
  pulse_energy = np.vstack(pulse_energy)
  pulse_energy = pulse_energy[np.argsort(pulse_energy[:,0])]

  fig = plt.figure(0)
  ax = []
  ax.append(plt.subplot2grid((1,1), (0,0)))
  ax[0].plot(pulse_energy[:,0],pulse_energy[:,1])
  plt.savefig("pulse_energy")
  plt.close()

def process_file(filename):
  sdf_data = sdf.SDF(filename).read()
  return (sdf_data['Header']['time'], integrate_pulse(sdf_data))

def integrate_pulse(sdf_data):
  x = sdf_data['Grid/Grid/X']
  y = sdf_data['Grid/Grid/Y']
  ey = sdf_data['Electric Field/Ey']
  ey2 = numpy.power(ey,2)
  y_int = np.asarray([np.trapz(ey2[a], y) for a in range(0,x.shape[0])])
  e_tot = np.trapz(y_int, x)
  return e_tot

 
def foo():
  fig = plt.figure(0)
  ax = []
  ax.append(plt.subplot2grid((2,3), (0,0), colspan=3))
  ax.append(plt.subplot2grid((2,3), (1,0), colspan=2))
  ax.append(plt.subplot2grid((2,3), (1,2), colspan=1))
  xmax, ymax = (0.0, 0.0)
  particle_tracks = shared_data[0]
  for a in range(0,len(particle_tracks)):
    ax[0].plot(particle_tracks[a][0],particle_tracks[a][2])
    xmax = xmax if particle_tracks[a][0].max() < xmax else particle_tracks[a][0].max()
    ymax = ymax if particle_tracks[a][2].max() < ymax else particle_tracks[a][2].max()
  
  im = ax[1].imshow(dens, vmin=1e20, vmax=1e22, extent=[x.min(), x.max(), y.min(), y.max()])
  for particle in particle_position:
   ax[0].scatter(particle[0],particle[2],color='k')
   ax[1].scatter(particle[0],particle[1],color='k')
  divider = make_axes_locatable(ax[1])
  cax = divider.append_axes('right', size='5%', pad=0.05)
  plt.colorbar(im, cax=cax)

  ax[2].plot(part_x,part_px,'k,')

## Label axes, set limits
  ax[0].set_xlim(0,xmax)
  ax[0].set_ylim(0,ymax)
  ax[0].set_xlabel("x / um")
  ax[0].set_ylabel("px / MeV/c")
  ax[1].set_xlabel("x / um")
  ax[1].set_ylabel("y / um")
  ax[2].set_xlim(x.min(),x.max())
  ax[2].set_ylim(0,ymax)
  ax[2].set_xlabel("x / um")
  ax[2].set_ylabel("px / MeV/c")


  x_px = 1920
  y_px = 1080
  y_size=10
  x_size=y_size*x_px / y_px
  fig.set_size_inches(x_size,y_size)
  savepath = os.path.join('movie',(filename[:-4]))
  print(savepath)
  plt.savefig(savepath,dpi=x_px/x_size)
  plt.close()
  
if __name__ == '__main__':
  main()
