#!/bin/bash

if [ ! -d "$1" ]; then
    echo "Are you on drugs? There's no such directory as $1"
    exit
fi

startdir="$PWD"
sourcedir=$(readlink -f $1)
simdir=$(echo $sourcedir | sed "s/.*$USER\/\(.*\)/\1/g")
workdir="$CCCWORKDIR/$simdir"
storedir="$CCCSTOREDIR"

cd $sourcedir

if [[ ! -d $workdir ]]; then
    mkdir $workdir
fi

if [[ ! -d $storedir ]]; then
    mkdir $storedir
fi

sdftarball="$(echo $simdir | sed 's#/#.#g').tar"
tar -c --tape-length=$((100*1024*1024)) -f $sdftarball -F ~/bin/tar_multifile *
mv ${sdftarball}* $storedir

for i in $(ls $sourcedir); do
    if [[ "$i" != *.sdf ]]; then
        cp -r $sourcedir/$i $workdir
    fi
done

cd $startdir
